// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/2/2025, 5:45:35 PM
const configMerger = require("C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/plugins/**/*.{js,ts,mjs}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/composables/**/*.{js,ts,mjs}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/utils/**/*.{js,ts,mjs}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ASUS/Documents/Work/Github/kutabeachhotel/app.config.{js,ts,mjs}"] } }));

module.exports = config
